apiVersion: v1

kind: ConfigMap

metadata:

  name: mongo-configmap

data:

  mongod-conf: |

    dbpath=/var/lib/mongodb

    logpath=/var/log/mongodb/mongodb.log

    logappend=true

    bind_ip = 0.0.0.0

    port = 27017

    journal=true

    auth = true