apiVersion: v1

kind: Service

metadata:

  creationTimestamp: null

  labels:

    app: tracking-server

  name: tracking-server

spec:

  ports:

  - port: 3000

    protocol: TCP

    targetPort: 3000

  selector:

    app: tracking-server

  type: ClusterIP

status:

  loadBalancer: {}

